// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBxLEI2C5vh0XMifZy0tWCoQdXBzAewBM',
    appId: '1:1077415531453:web:814fd2185f2a2aebe078d4',
    messagingSenderId: '1077415531453',
    projectId: 'mynewchat-7c367',
    authDomain: 'mynewchat-7c367.firebaseapp.com',
    databaseURL: 'https://mynewchat-7c367.firebaseio.com',
    storageBucket: 'mynewchat-7c367.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWBjLMQ9Vi7-y3maXGrWHn6NNm_r4i16M',
    appId: '1:1077415531453:android:fbbd1ea8c6a5ed96e078d4',
    messagingSenderId: '1077415531453',
    projectId: 'mynewchat-7c367',
    databaseURL: 'https://mynewchat-7c367.firebaseio.com',
    storageBucket: 'mynewchat-7c367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDasQI9iUXug5TIUTMdoRivpW5apS8Wqic',
    appId: '1:1077415531453:ios:b67d6834c036c6e4e078d4',
    messagingSenderId: '1077415531453',
    projectId: 'mynewchat-7c367',
    databaseURL: 'https://mynewchat-7c367.firebaseio.com',
    storageBucket: 'mynewchat-7c367.appspot.com',
    iosBundleId: 'com.example.toDoAppC11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDasQI9iUXug5TIUTMdoRivpW5apS8Wqic',
    appId: '1:1077415531453:ios:b67d6834c036c6e4e078d4',
    messagingSenderId: '1077415531453',
    projectId: 'mynewchat-7c367',
    databaseURL: 'https://mynewchat-7c367.firebaseio.com',
    storageBucket: 'mynewchat-7c367.appspot.com',
    iosBundleId: 'com.example.toDoAppC11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBxLEI2C5vh0XMifZy0tWCoQdXBzAewBM',
    appId: '1:1077415531453:web:8714db2cf6bb099ce078d4',
    messagingSenderId: '1077415531453',
    projectId: 'mynewchat-7c367',
    authDomain: 'mynewchat-7c367.firebaseapp.com',
    databaseURL: 'https://mynewchat-7c367.firebaseio.com',
    storageBucket: 'mynewchat-7c367.appspot.com',
  );

}